USE master
GO
IF DB_ID('StudentSystemManagement') IS NOT NULL
	DROP DATABASE StudentSystemManagement
GO
CREATE DATABASE StudentSystemManagement
GO
USE StudentSystemManagement
GO
CREATE TABLE SINHVIEN
(
	MSSV INT PRIMARY KEY,
	HoTen nvarchar(MAX),
	GioiTinh nchar(5) CHECK (GioiTinh = 'Nam' OR GioiTinh = N'Nữ'),
	CMND char(11),
	MaLop char(6)
)

CREATE TABLE LOPHOC
(
	MaLop char(6) PRIMARY KEY,
	TenLop nvarchar(MAX)
)

CREATE TABLE MONHOC
(
	MaMonHoc char(6) PRIMARY KEY,
	TenMonHoc nvarchar(MAX)
)

CREATE TABLE CHITIETMONHOC
(
	MSSV int,
	MaMonHoc char(6),
	PhongHoc char(6),
	PRIMARY KEY(MSSV, MaMonHoc)
)

CREATE TABLE DIEM
(
	MSSV int,
	MaMonHoc char(6),
	DiemGk float,
	DiemCK float,
	DiemKhac float,
	PRIMARY KEY(MSSV, MaMonHoc)
)

CREATE TABLE TAIKHOAN
(
	USERNAME char(8) PRIMARY KEY,
	[PASSWORD] nvarchar(MAX),
	TYPE int
)

GO
ALTER TABLE SINHVIEN
	ADD CONSTRAINT FK_SINHVIEN_MaLop
	FOREIGN KEY (MaLop) REFERENCES LOPHOC(MaLop)

ALTER TABLE DIEM
	ADD CONSTRAINT FK_DIEM_MSSV
	FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV)

ALTER TABLE DIEM
	ADD CONSTRAINT FK_DIEM_MaMonHoc
	FOREIGN KEY (MaMonHoc) REFERENCES MonHoc(MaMonHoc)

ALTER TABLE CHITIETMONHOC
	ADD CONSTRAINT FK_CHITIETMONHOC_MSSV
	FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV)

ALTER TABLE CHITIETMONHOC
	ADD CONSTRAINT FK_CHITIETMONHOC_MaMonHoc
	FOREIGN KEY (MaMonHoc) REFERENCES MonHoc(MaMonHoc)

GO
INSERT INTO TAIKHOAN VALUES ('giaovu', 'giaovu', 0)
GO
SELECT * FROM MONHOC
SELECT * FROM CHITIETMONHOC
DELETE TOP(10) FROM MONHOC
DELETE TOP(10) FROM LOPHOC